### ISSUE TITLE
duplicate module of Content Moderation?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/workbench_moderation#1]
This module seems to be a duplicate of https://github.com/backdrop-contrib/content_moderation, which is a fork of workbench moderation. Would you like to join forces @juanolalla ?

The aim of the fork is to have a better name and not be tied to the rest of workbench if not wanted, but it's basically the same. It still needs a little bit of work but is close.

**Comment by herbdool** [comment]
Content moderation also has an upgrade path from Workbench moderation so someone wouldn't lose the config in an upgrade.

The only remaining issue is dealing with the new active revision state that Backdrop has, and reconciling it with the drupal/workbench approach.

So by joining forces, would you like to be a maintainer of content moderation?

**Comment by juanolalla** [comment]
@herbdool Yes of course! I didn't know about this. I'll close the other project so no one get confused. Glad to help

I also started workbench module porting. Is there any other workbench port I should know about?

**Comment by herbdool** [comment]
@juanolalla great! That's the only workbench port I worked on.

**Comment by herbdool** [comment]
@juanolalla I've added you to the other module as a maintainer.
